### ISSUE TITLE
[S1] Estudar ferramentas para desenvolver a aplicação

### ISSUE THREAD

**Issue by liliangoncalves** [Lilikamary/engenhariadesoftware#8]
Feito estudo com alguns frameworks para automatização na criação dos CRUDs.
Estudado o Deimoselle, Grails/Groovy, porém devido a incompatibilidade de versão do JAVA, optou-se pelo netbeans, gerando o JPA com persistência de dados em banco de Dados Postgresql, JSF para interface com Primefaces, devido conhecimento adquirido em capacitação realizada em 2005 e 2015 pela desenvolvedora.

**Comment by liliangoncalves** [comment]
Para Documentação.

**Comment by monicaauricelia** [comment]
Escolhida a IDE Netbeans pela facilidade de criação das classes, JPA, com persistência no banco através de hibernate, JSF com primefaces, Banco de Dados Postgresql
